Rcsa.Web/Controllers/StandardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Rcsa.Web.Models;
using WebMatrix.WebData;
using System.Data.Objects.SqlClient;
using System.ComponentModel.DataAnnotations;
using Rcsa.Web.ReportForms;
using LinqKit;
using System.Linq.Expressions;
using System.Web.Security;

namespace Rcsa.Web.Controllers
{
    [Authorize]
    public class StandardController : Controller
    {
        //
        // GET: /Standard/
        RcsaDb db = new RcsaDb();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult StandardReports()
        {
            var reportList = new SelectList(new[]
                                                {
                                              new {ID="1",Name="Has Action Plan"},
                                              new{ID="2",Name="Very High or High Inherent Risk Rating and Mitigant Importance"},
                                              new{ID="3",Name="Issue Severity: High"},
                                              new{ID="4",Name="Issue Severity:Very High"},
                                              new{ID="5",Name="Mitigant Effectiveness: Effective"},
                                              new{ID="6",Name="Subrisk Impact: High"},
                                              new{ID="7",Name="Subrisk Impact: Very High"},
                                              new{ID="8",Name="Subrisk Likelihood: High"},
                                              new{ID="9",Name="Subrisk Likelihood: Very High"},
                                              new{ID="10",Name="Accepted Risk Report"},
                                              new{ID="11",Name="Loss Reporting Report"},
                                              new{ID="12",Name="Risk Assessment Report"},
                                          },
                          "ID", "Name", 1);
            ViewData["list"] = reportList;
            List<RiskManagementModel> list = new List<RiskManagementModel>();
            var roles = Roles.GetRolesForUser().Single();
            if (roles.ToLower() == "Company")
            {



                var companyUserId = db.CompanyUsers.Where(x => x.UserId == WebSecurity.CurrentUserId).SingleOrDefault();
                var riskDetail = db.RiskDetails.Where(x => x.CompanyID == companyUserId.CompanyId).ToList();
                foreach (var riskDetailResult in riskDetail)
                {
                    if (riskDetailResult != null && riskDetailResult.RiskDetailID > 0)
                    {
                        var model = new RiskManagementModel();
                        model.RiskDetailID = riskDetailResult.RiskDetailID;
                        model.CompanyId = riskDetailResult.CompanyID ?? 0;
                        model.DepartmentID = riskDetailResult.DepartmentID ?? 0;
                        model.RiskID = riskDetailResult.RiskID ?? 0;
                        model.RiskName = riskDetailResult.RiskMaster.RiskName;
                        model.SubRiskID = riskDetailResult.SubRiskID ?? 0;
                        model.SubRiskName = riskDetailResult.SubRiskMaster.SubRiskName;
                        model.SubRisk_Impact = riskDetailResult.SubRisk_Impact;
                        model.SubRisk_Likelyhood = riskDetailResult.SubRisk_Likelyhood;
                        model.Inherenet_risk_rating = riskDetailResult.Inherenet_risk_rating;
                        model.MitigantID = riskDetailResult.MitigantID ?? 0;
                        model.MitigantName = riskDetailResult.MitigantMaster.MitigantName;
                        model.MitigantDescription = riskDetailResult.MitigantMaster.MitigantDesc;
                        model.Mitigant_Importance = riskDetailResult.Mitigant_Importance;
                        model.Mitigant_effectiveness = riskDetailResult.Mitigant_effectiveness;
                        model.Issue = riskDetailResult.Issue;
                        model.Issue_Severity = riskDetailResult.Issue_Severity;
                        model.ActionPlanAvailable = riskDetailResult.ActionPlanAvailable;
                        model.ActionPlan = riskDetailResult.ActionPlan;
                        model.TargetDate = riskDetailResult.TargetDate.ToString();
                        model.ActionPlan_Status = riskDetailResult.ActionPlan_Status;
                        model.List_risk_associated = riskDetailResult.List_risk_associated;
                        model.Owner = riskDetailResult.Owner;
                        if (riskDetailResult.CompletionDate == null)
                        {
                            model.CompletionDate = (new DateTime()).ToString();
                        }
                        else
                        {
                            model.CompletionDate = riskDetailResult.CompletionDate.ToString();
                        }
                        list.Add(model);
                    }
                }
            }
            else
            {
                var riskDetails = db.RiskDetails.ToList();
                foreach (var riskDetail in riskDetails)
                {
                    if (riskDetails.Count > 0)
                    {
                        var model = new RiskManagementModel();
                        model = new RiskManagementModel();
                        model.RiskDetailID = riskDetail.RiskDetailID;
                        model.CompanyId = riskDetail.CompanyID ?? 0;
                        model.DepartmentID = riskDetail.DepartmentID ?? 0;
                        model.RiskID = riskDetail.RiskID ?? 0;
                        model.RiskName = riskDetail.RiskMaster.RiskName;
                        model.SubRiskID = riskDetail.SubRiskID ?? 0;
                        model.SubRiskName = riskDetail.SubRiskMaster.SubRiskName;
                        model.SubRisk_Impact = riskDetail.SubRisk_Impact;
                        model.SubRisk_Likelyhood = riskDetail.SubRisk_Likelyhood;
                        model.Inherenet_risk_rating = riskDetail.Inherenet_risk_rating;
                        model.MitigantID = riskDetail.MitigantID ?? 0;
                        model.MitigantName = riskDetail.MitigantMaster.MitigantName;
                        model.MitigantDescription = riskDetail.MitigantMaster.MitigantDesc;
                        model.Mitigant_Importance = riskDetail.Mitigant_Importance;
                        model.Mitigant_effectiveness = riskDetail.Mitigant_effectiveness;
                        model.Issue = riskDetail.Issue;
                        model.Issue_Severity = riskDetail.Issue_Severity;
                        model.ActionPlanAvailable = riskDetail.ActionPlanAvailable;
                        model.ActionPlan = riskDetail.ActionPlan;
                        model.TargetDate = riskDetail.TargetDate.ToString();
                        model.ActionPlan_Status = riskDetail.ActionPlan_Status;
                        model.List_risk_associated = riskDetail.List_risk_associated;
                        model.Owner = riskDetail.Owner;
                        list.Add(model);
                    }
                }
            }
            return View();
        }

        [HttpPost]
        public string ReportResult(string compId, string deptId, string reportType, string value)
        {
            string res = "0";

            int companyId = 0;
            if (compId != "Select Company" && compId != "")
            {
                companyId = Convert.ToInt32(compId);
            }
            int departmentId = 0;
            if (deptId != "Select Department" && deptId != "")
            {
                departmentId = Convert.ToInt32(deptId);
            }
            List<StandardReportModel> list = new List<StandardReportModel>();
            var roles = Roles.GetRolesForUser().Single();
            var lstRiskDetalModel = new List<RiskDetailsModel>();

            List<RiskDetailsModel> riskDetailsData;
            List<CompanyMaster> companiesList = new List<CompanyMaster>();
            if (User.IsInRole("Admin"))
            {

                if (reportType == "1")
                {
                    riskDetailsData = db.RiskDetails.Where(x => x.CompanyID == companyId && x.DepartmentID == departmentId && x.ActionPlanAvailable == "Yes").ToList();

                }
                else if (reportType == "2")
                {
                    riskDetailsData = db.RiskDetails.Where(x => x.CompanyID == companyId && x.DepartmentID == departmentId &&
                      (x.Mitigant_Importance == "VH" || x.Mitigant_Importance == "H") && (x.Inherenet_risk_rating == "VH" || x.Inherenet_risk_rating == "H")).ToList();
                }
                else if (reportType == "3")
                {
                    riskDetailsData = db.RiskDetails.Where(x => x.CompanyID == companyId && x.DepartmentID == departmentId && x.Issue_Severity == "H").ToList();
                }
                else if (reportType == "4")
                {
                    riskDetailsData = db.RiskDetails.Where(x => x.CompanyID == companyId && x.DepartmentID == departmentId && x.Issue_Severity == "VH").ToList();
                }
                else if (reportType == "5")
                {
                    riskDetailsData = db.RiskDetails.Where(x => x.CompanyID == companyId && x.DepartmentID == departmentId
                        && x.Mitigant_effectiveness == "Effective").ToList();
                }
                else if (reportType == "6")
                {

Rcsa.Web/Views/Standard/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Rcsa.Web/Views/Standard/SpecificRiskDetails.cshtml
@using Rcsa.Web.Models
@model IEnumerable<Rcsa.Web.Models.RiskManagementModel>
@{
    ViewBag.Title = "RiskManagement";
    Layout = "~/Views/Shared/_SubLayout.cshtml";
    var db = new Rcsa.Web.Models.RcsaDb();
    int compId = Convert.ToInt32(ViewBag.compId) != 0 ? Convert.ToInt32(ViewBag.compId) : 0;
    int deptId = Convert.ToInt32(ViewBag.deptId) != 0 ? Convert.ToInt32(ViewBag.deptId) : 0;
    var userProfiles = db.UserProfiles.FirstOrDefault(x => x.UserId == WebSecurity.CurrentUserId);
    int riskAssesmentId = Convert.ToInt32(ViewBag.RiskAssesmentId) != 0 ? Convert.ToInt32(ViewBag.RiskAssesmentId) : 0;
    var riskDetails = db.RiskAssessmentMaster.Where(x => x.RiskAssessmentId == riskAssesmentId).SingleOrDefault();
    int lastUpdateId = Convert.ToInt32(ViewBag.lastId) != 0 ? Convert.ToInt32(ViewBag.lastId) : 0;
    // int value  =Url.RequestContext.HttpContext.Request.QueryString.AllKeys.Contains("ReturnUrl");
    string value = Request.QueryString["editId"];
    RiskManagementModel model = new RiskManagementModel();
    RcsaDb db1 = new RcsaDb();
    ViewBag.Title = "Users Report";
    
}

<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script type="text/javascript">
    $(function () {

        $('#btnSearch').click(function () {
            debugger;
            var comp = $('#hfCompId').val();
            var dept = $('#hfDeptId').val();
            var riskAssessmentName = $('#hfRiskAssesmentId').val();
            var riskRate = $('#ddlInherentRiskRating option:selected').val();
            var issueSave = $('#ddlIssueSeverity option:selected').val();
            var subriskImp = $('#ddlSubriskImpact option:selected').val();
            var subrisklike = $('#ddlSubriskLikelihood option:selected').val();
            var mitigant = $('#ddlMitigantImportance option:selected').val();
            var reportType = $('#ddlReportTye option:selected').val();
            var reportTypeValue = $('#ddlReportTye option:selected').text();
            var winW = $(window).width() - 15;
            var winH = $(window).height() - 15;
            $.ajax({
                url: '../../Standard/SpecificRiskDetails',
                data: JSON.stringify({
                    compId: comp, deptId: dept, riskAssessmentName: riskAssessmentName, reportType: reportType, value: reportTypeValue
                }),
                type: 'POST',
                contentType: 'application/json;',
                dataType: 'json',
                async: false,
                success: function (response) {
                    debugger;
                    $('#error').hide();
                    var v = response;
                    if (v == "1") {
                        $('#reportData').attr('src', '/ReportForms/CustomizedReport.aspx');
                        $("#Dialog").dialog({
                            position: { my: "center", at: "center", of: "center" },
                            top: 30,
                            left: 50,
                            width: winW,
                            height: winH,
                            modal: true,
                            title: 'Report'
                        });
                        return false;
                    }
                    else {
                        $('#Dialog').hide();
                        //$('#reportData').hide();
                        $('#error').show();
                        return false;
                    }
                }
            });
        });

    });


</script>

<style>
    select
    {
        width: 100px;
    }

    textarea, input[type=text]
    {
        width: 100px;
        border-radius: 5px;
        box-shadow: 0px 0px;
        border: 1px solid silver;
        padding: 2px 5px;
        margin-bottom: 5px;
    }

    input[type=text]
    {
        height: 30px;
    }

    textarea
    {
        height: 60px;
    }

    .highlight
    {
        background-color: lightblue !important;
    }
</style>
<link href="~/Content/grid.css" rel="stylesheet" />
<h3 class="upcoming-head" style="margin-bottom: 15px; text-align: center;">Specific Risk Type Report</h3>

@using (Html.BeginForm())
{
   
   
    
    <input type="hidden" id="hfCompId" name="hfCompId" value="@compId" />
    <input type="hidden" id="hfDeptId" name="hfDeptId" value="@deptId" />
    <input type="hidden" id="hfRiskAssesmentId" name="hfRiskAssesmentId" value="@riskAssesmentId" />
    <input type="hidden" id="hfRiskId" name="hfRiskId" value="0" />
    <input type="hidden" id="hfSubRiskId" name="hfSubRiskId" value="0" />
    <input type="hidden" id="hfMitigantId" name="hfMitigantId" value="0" />
    <input type ="hidden" id="gfvalue" name="hfname" value="@value"/>
   
    <div>
        <table id="hor-minimalist-b" cellpadding="2" cellspacing="2">
            <tr>
                <td >
                    <strong>Company Name:</strong>
                </td>
                <td >
                    @ViewBag.companyName
                </td>
                <td>
                    <strong>Department Name:</strong>

                </td>
                <td align="left">
                    @ViewBag.departmentName
                </td>                

            </tr>
            <tr>
                <td>
                    <strong>Risk Assessment Name:</strong> 

                </td>
                <td colspan="3">
                    @ViewBag.riskheaderName
                </td>
            </tr>
            <tr>
                <th scope="col" colspan="4">Report Type</th>
            </tr>
            <tr>
                <td colspan="4">
                    @Html.DropDownList("list", ViewData["list"] as SelectList, new { id = "ddlReportTye", style = "width:240px;height:24px;" })
                </td>
            </tr>

        </table>
        <div style="clear: both;">&nbsp;</div>
        <input type="button" id="btnSearch" value="Show Report" class="button1" />
    </div>
    <div id="Dialog" style="display: none; min-height: 600px; width: 98%">
        <iframe id="reportData" height="95%" style="border: 0px; width: 98%"></iframe>
    </div>
    <div id="error" class="error1" style="display: none;">No records found!!!</div>
 
}

Rcsa.Web/Views/Standard/SpecificTypeRisk.cshtml
@model IEnumerable<Rcsa.Web.Models.RiskAssessmentMaster>

@{
    ViewBag.Title = "SpecificTypeRisk";
    Layout = "~/Views/Shared/_SubLayout.cshtml";
    var db = new Rcsa.Web.Models.RcsaDb();
    List<Rcsa.Web.Models.CompanyMaster> companyMaster = new List<Rcsa.Web.Models.CompanyMaster>();
    Rcsa.Web.Models.RiskAssessmentMaster riskHeader = new Rcsa.Web.Models.RiskAssessmentMaster();
    var details = db.RiskDetails.ToList();
    int compId = ViewBag.CompId != null ? Convert.ToInt32(ViewBag.CompId) : 0;
    int deptId = ViewBag.DeptId != null ? Convert.ToInt32(ViewBag.DeptId) : 0;
    var UserDepartments = new List<int>();
    if (User.IsInRole("Admin"))
    {
        companyMaster = db.CompaniesMaster.ToList();
    }
    if (User.IsInRole("Consultant"))
    {
        companyMaster = db.CompaniesMaster.ToList();
        //var companyUsers = db.CompanyUsers.Where(x => x.CreatedBy == WebSecurity.CurrentUserId).ToList();
        //if (companyUsers != null && companyUsers.Count > 0)
        //{
        //    foreach (var item in companyUsers)
        //    {
        //        var company = db.CompaniesMaster.FirstOrDefault(x => x.CompanyId == item.CompanyId);
        //        companyMaster.Add(company);
        //    }
        //}
    }
    if (User.IsInRole("Manager") || User.IsInRole("User"))
    {
        UserDepartments = db.UserDepartments.Where(x => x.UserId == WebSecurity.CurrentUserId).Select(x => x.DepartmentId).ToList();
        var companyUsers = db.CompanyUsers.Where(x => x.UserId == WebSecurity.CurrentUserId).ToList();
        compId = companyUsers.FirstOrDefault().CompanyId;
        if (companyUsers != null && companyUsers.Count > 0)
        {
            foreach (var item in companyUsers)
            {
                var company = db.CompaniesMaster.FirstOrDefault(x => x.CompanyId == item.CompanyId);
                companyMaster.Add(company);
            }
        }
    }


}

<script>
    $(document).ready(function () {
        //var compId = $('#ddlCompany option:selected').val();
        //if (compId > 0) {
        //    $('#ddlDepartments').removeAttr("disabled");
        //}

        //loadgrid();

        $("#ddlCompany").change(function () {
            //alert("company");
            loadgrid();
            var Param = { CompanyId: $('#ddlCompany option:selected').attr("value") };
            $.getJSON("/CompanyUsersReport/DepartmentList/", Param, function (data) {
                var items = "<option>Select Department</option>";
                $.each(data, function (i, data) {
                    items += "<option value=" + data.Value + ">" + data.Text + "</option>";
                    $('#ddlDepartments').removeAttr("disabled");
                });
                $("#ddlDepartments").html(items);
            });
        });

        var deptId = $('#ddlDepartments option:selected').val();
        if (deptId != "") {
            $('#searchBoxDivs').show();
            // $('#gridData').show();
        }
        else {
            $('#searchBoxDivs').hide();
            //$('#gridData').hide();
        }
    });

    function loadgrid() {
        debugger;
        var compId = $('#ddlCompany option:selected').val();
        var deptId = $('#ddlDepartments option:selected').val();
        $.ajax({
            url: '../../Standard/GetAllRiskAssessmentList',
            data: JSON.stringify({ compId: compId, deptId: deptId }),
            type: 'POST',
            contentType: 'application/json;',
            dataType: 'json',
            async: false,
            success: function (response) {
                debugger;
                var v = response;
                if (v == "1") {
                    $('#hfCompId').val(compId);
                    $('#hfDeptId').val(deptId);
                    $('#searchBoxDivs').show();
                    $('#gridData').show();
                    $('form').submit();
                }
                else {
                    $('#hfCompId').val(compId);
                    $('#hfDeptId').val(deptId);
                    $('#searchBoxDivs').show();
                    $('#gridData').show();
                    $('form').submit();
                    //$('#riskAlreadyinprogress').show();
                    //$('#searchBoxDivs').hide();
                    //$('#gridData').hide();
                    //$('#RiskAssesmentDiv').hide();

                    return false;
                }
            }
        });


    }

    //function displayNewRiskAssesment() {
    //    var compId = $('#ddlCompany option:selected').val();
    //    var deptId = $('#ddlDepartments option:selected').val();
    //    $('#hfCompId').val(compId);
    //    $('#hfDeptId').val(deptId);
    //    $('#ddlCompany').attr('disabled', 'disabled');
    //    $('#ddlDepartments').attr('disabled', 'disabled');
    //    $('#searchBoxDivs').hide();
    //    $('#RiskAssesmentDiv').show();

    //}

    function cancelRiskAssesment() {
        $('#ddlCompany').removeAttr("disabled");
        $('#ddlDepartments').removeAttr("disabled");
        $('#searchBoxDivs').show();
        $('#RiskAssesmentDiv').hide();
    }
    //$("#btnCancel").click(function () {
    //    $('#ddlCompany').removeAttr("disabled");
    //    $('#ddlDepartments').removeAttr("disabled");
    //    $('#searchBoxDiv').show();
    //    $('#RiskAssesmentDiv').hide();
    //});


</script>
<link href="~/Content/grid.css" rel="stylesheet" />
<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center">Specific Type Risk Report</h3>

@using (Html.BeginForm())//"SpecificTypeRisk", "Standard", new { cId = @compId, dId = @deptId }
{    
    <input type="hidden" id="hfCompId" name="hfCompId" value="0" />
    <input type="hidden" id="hfDeptId" name="hfDeptId" value="0" />
    <div style="width: 100%;">
        <div id="divDepartment" class="divrows">
            @if (User.IsInRole("Manager") || User.IsInRole("User"))
            {   
                <div class="divpanel" style="display: none">
                    <div align="left">
                        <ul class="rlist">
                            <li class="litem">Company</li>
                            <li style="text-align: left;">
                                @Html.DropDownList("ddlCompany", new SelectList(@companyMaster, "CompanyId", "ComapnyName", @compId),
                                "-- Select Company -- ", new { id = "ddlCompany", style = "width:240px;" })
                            </li>
                        </ul>
                    </div>
                </div> 
                <div class="divpanel">
                    <div align="left">
                        <ul class="rlist">
                            <li class="litem">Department</li>
                            <li style="text-align: left;">
                                @*@if (User.IsInRole("User"))
                                {*@
                                    @Html.DropDownList("ddlDepartments", new SelectList(db.DepartmentsMaster.Where(x => x.CompanyId == @compId && UserDepartments.Contains(x.DepartmentId)).ToList(),
                               "DepartmentId", "DepartmentName", @deptId), "-- All Departments -- ",
                                new { id = "ddlDepartments", onchange = "loadgrid()", style = "width:240px;" })
                                @*}
                                else
                                {
                                    @Html.DropDownList("ddlDepartments", new SelectList(db.DepartmentsMaster.Where(x => x.CompanyId == @compId).ToList(),
                               "DepartmentId", "DepartmentName", @deptId), "-- All Departments -- ",
                                new { id = "ddlDepartments", onchange = "loadgrid()", style = "width:240px;" })
                                }*@
                            </li>
                        </ul>
                    </div>
                </div>       
            }
            else
            {
                <div class="divpanel">
                    <div align="left">
                        <ul class="rlist">
                            <li class="litem">Company</li>
                            <li style="text-align: left;">
                                @Html.DropDownList("ddlCompany", new SelectList(@companyMaster, "CompanyId", "ComapnyName", @compId),
                                "-- Select Company -- ", new { id = "ddlCompany", style = "width:240px;" })
                            </li>
                        </ul>
                    </div>
                </div> 
                <div class="divpanel">
                    <div align="left">
                        <ul class="rlist">
                            <li class="litem">Department</li>
                            <li style="text-align: left;">
                                @Html.DropDownList("ddlDepartments", new SelectList(db.DepartmentsMaster.Where(x => x.CompanyId == @compId).ToList(),
                               "DepartmentId", "DepartmentName", @deptId), "-- All Department -- ", new
                               {
                                   id = "ddlDepartments",
                                   onchange = "loadgrid()",
                                   style = "width:240px;"
                               })
                            </li>
                        </ul>
                    </div>
                </div>
            }
        </div>
    </div>
       
    <div id="riskAlreadyinprogress" class="message error" style="display: none">
        <h4>Sorry you can not add a risk. A risk with this department is already in progress!</h4>
    </div>@*       
        
    <div class="searchBoxDiv" id="searchBoxDivs" style="display: none">
        <span style="float: right; margin-top: 6px; margin-right: 18px;"><strong><u>
            <a href="#" onclick="displayNewRiskAssesment()">Start New</a>
          
        </u></strong>
        </span>
    </div>  
    
    *@<div class="divrows" id="RiskAssesmentDiv" style="display: none">
        <div class="divpanel">
            <div align="left">
                <ul class="rlist">
                    <li class="litem">Risk Assessment Name</li>
                    <li style="text-align: left;">
                        <input type="text" id="txtRiskAssesmentName" value="" name="txtRiskAssesmentName" placeholder="Risk Assessment Name"
                            style="width: 238px; height: 24px; margin-bottom: 20px;" />
                    </li>
                </ul>
            </div>
            <span style="margin-left: -164px;">
                <input type="submit" value="Save & Continue" id="btnSave" class="searchButton" style="width: 115px;" />
                <input type="button" id="btnCancel" value="Cancel" class="searchButton" onclick="cancelRiskAssesment()" /></span>
        </div>
    </div>  
             
}
<div style="height: 25px;"></div>
<div id="gridData" style="display: block">
    <table class="minilist-b">
        <tr>
            <td>
                <div id="dvGrid">
                    @if (Model != null)
                    {
                        var gridTest = new WebGrid(Model, canPage: true, canSort: false, rowsPerPage: 10, ajaxUpdateContainerId: "dvGrid");
                        // gridTest.Bind(Model, rowCount: 3, autoSortAndPage: true);
                        // gridTest.Pager(mode: WebGridPagerModes.All);
                        //  <div id="myGrid">
                        @gridTest.GetHtml(
                           tableStyle: "mGrid",
                            alternatingRowStyle: "mGrid-alternating-row",
                            footerStyle: "pagination",
                            mode: WebGridPagerModes.All,
                            numericLinksCount: 10,
                             firstText: "First",
                             lastText: "Last",
                             previousText: "Prev",
                             nextText: "Next",
                columns: new[]{
                    gridTest.Column("InsertedDate", header: "Date", format: (item) => String.Format("{0:MM/dd/yyyy}", item.InsertedDate)),
                    gridTest.Column("RiskAssessmentName", header: "Name"),
                    gridTest.Column("Status", header: "Status", format: (item) => (item.Status != "C" ? "In Progress" : "Completed")),
                    gridTest.Column("", header: "", style: "grdSrNo",
                    format: @<text>
                        <div>
                            @if (!User.IsInRole("Manager") || User.IsInRole("User"))
                            {  
                                @Html.ActionLink("View", "SpecificRiskDetails", new { id = item.RiskAssessmentId, compId = @compId, deptId = @deptId })
                            }
                            else
                            {
                                @Html.ActionLink("View", "SpecificRiskDetails", new { id = item.RiskAssessmentId, compId = @compId, deptId = @deptId })
                            }
                        </div>
                        </text>
)
})
                        // </div>
                    }
                    else
                    {
                        <span><b>No Record Found!!!</b></span>
                    }
                </div>
                <style>
                    .grdSrNo
                    {
                        width: 25%;
                        text-align: center;
                    }
                </style>
            </td>
        </tr>
    </table>
</div>