Rcsa.Web/Controllers/OrmController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Linq;
using Rcsa.Web.Models;
using WebMatrix.WebData;
using System.Runtime.Serialization;

namespace Rcsa.Web.Controllers
{
  [Authorize]
  public class OrmController : Controller
  {
    //
    // GET: /Orm/
    RcsaDb db = new RcsaDb();

    public ActionResult Index()
    {
      return View();
    }

    public ActionResult RiskManagement(int id, int? compId, int? deptId)
    {
      ViewBag.compId = compId;
      ViewBag.deptId = deptId;

      var model = new RiskManagementModel();
      var company = db.CompanyUsers.Where(x => x.UserId == WebSecurity.CurrentUserId);
      if (!company.Any())
      {
        return View(model);
      }

      var companyId = company.First().CompanyId;
      RiskDetailsModel riskDetail = db.RiskDetails.FirstOrDefault(x => x.RiskDetailID == id && x.CompanyID == companyId);
      if (riskDetail != null && riskDetail.RiskDetailID > 0)
      {
        ViewBag.Mode = "Edit";
        model.RiskDetailID = riskDetail.RiskDetailID;
        model.CompanyId = riskDetail.CompanyID ?? 0;
        model.DepartmentID = riskDetail.DepartmentID ?? 0;
        model.RiskID = riskDetail.RiskID ?? 0;
        RiskMaster objRiskMaster = riskDetail.RiskMaster;
        if (objRiskMaster != null)
        {
          model.RiskName = objRiskMaster.RiskName;
          model.RiskDescription = objRiskMaster.Description;
          objRiskMaster = null;
        }
        model.SubRiskID = riskDetail.SubRiskID ?? 0;
        SubRiskMaster objSubRiskMaster = riskDetail.SubRiskMaster;
        if (objSubRiskMaster != null)
        {
          model.SubRiskName = objSubRiskMaster.SubRiskName;
          model.SubRiskDescription = objSubRiskMaster.SubRiskDesc;
          objSubRiskMaster = null;
        }
        model.SubRisk_Impact = riskDetail.SubRisk_Impact;
        model.SubRisk_Likelyhood = riskDetail.SubRisk_Likelyhood;
        model.Inherenet_risk_rating = riskDetail.Inherenet_risk_rating;
        model.MitigantID = riskDetail.MitigantID ?? 0;
        MitigantMaster objMitigantMaster = riskDetail.MitigantMaster;
        if (objMitigantMaster != null)
        {
          model.MitigantName = objMitigantMaster.MitigantName;
          model.MitigantDescription = objMitigantMaster.MitigantDesc;
          objMitigantMaster = null;
        }
        model.Mitigant_Importance = riskDetail.Mitigant_Importance;
        model.Mitigant_effectiveness = riskDetail.Mitigant_effectiveness;
        model.Mitigant_whyEffective = riskDetail.Mitigant_whyEffective;
        model.Issue = riskDetail.Issue;
        model.Issue_Severity = riskDetail.Issue_Severity;
        model.ActionPlanAvailable = riskDetail.ActionPlanAvailable;
        model.IsThisRiskBeingAccepted = riskDetail.IsThisRiskBeingAccepted;
        model.LossesAssociatedWithThisRisk = riskDetail.LossesAssociatedWithThisRisk;
        model.Losses = riskDetail.Losses;

        model.ActionPlan = riskDetail.ActionPlan;
        model.TargetDate = riskDetail.TargetDate.ToString();
        model.ActionPlan_Status = riskDetail.ActionPlan_Status;
        model.Reason_Risk_acceptance = riskDetail.Reason_Risk_acceptance;
        model.List_risk_associated = riskDetail.List_risk_associated;
        model.Owner = riskDetail.Owner;
        model.Shared_process_Department = riskDetail.Shared_process_Department;
        model.Shared_process_Description = riskDetail.Shared_process_Description;
        model.insertedBy = riskDetail.insertedBy ?? 0;
        model.Insertedon = DateTime.Now;
        model.insertedmachineinfo = riskDetail.insertedmachineinfo;
        model.Updatedby = riskDetail.Updatedby ?? 0;
        model.updatedon = DateTime.Now;
        model.updatemachineinfo = riskDetail.updatemachineinfo;
        model.CompanyObjectives = riskDetail.CompanyObjectives;
      }
      else
      {
        var com = db.CompanyUsers.Where(x => x.UserId == WebSecurity.CurrentUserId);
        if (com.Any())
        {
          model.CompanyId = com.First().CompanyId;
          model.TargetDate = DateTime.Now.ToString(); ;
        }
        model.TargetDate = DateTime.Now.ToString();
      }

      model.Departments = (from x in db.UserDepartments
                           join u in db.DepartmentsMaster on x.DepartmentId equals u.DepartmentId
                           where x.UserId == WebSecurity.CurrentUserId
                           select u).ToList();



      if (model.RiskID > 0)
      {
        model.Risks = db.RiskMasters.ToList();
        model.SubRisks = db.SubRisksMaster.Where(x => x.RiskId == model.RiskID).ToList();
      }
      else
      {
        model.Risks = new List<RiskMaster>();
        model.SubRisks = new List<SubRiskMaster>();
      }

      if (model.SubRiskID > 0)
        model.Mitigants = db.MitigantsMaster.Where(x => x.SubRiskId == model.SubRiskID).ToList();
      else
        model.Mitigants = new List<MitigantMaster>();

      //model.Shared_process_Departments = db.DepartmentsMaster.ToList();
      model.Shared_process_Departments = model.Departments;

      return View(model);
    }

    [HttpPost]
    public ActionResult RiskManagement(RiskManagementModel riskModel, string command)
    {
      string ip = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
      if (String.IsNullOrWhiteSpace(ip))
      {
        ip = Request.ServerVariables["REMOTE_ADDR"];
      }
      int? cid = Request["hfCompId"] != "" ? Convert.ToInt32(Request["hfCompId"]) : 0;
      int? did = Request["hfDeptId"] != "" ? Convert.ToInt32(Request["hfDeptId"]) : 0;
      int? rid = Request["hfAssesmentId"] != "" ? Convert.ToInt32(Request["hfAssesmentId"]) : 0;
      int riskId = Request["hfRiskId"] != "" ? Convert.ToInt32(Request["hfRiskId"]) : 0;
      int subRiskId = Request["hfSubRiskId"] != "" ? Convert.ToInt32(Request["hfSubRiskId"]) : 0;
      int mitigantId = Request["hfMitigantId"] != "" ? Convert.ToInt32(Request["hfMitigantId"]) : 0;
      if (ModelState.IsValid)
      {
        var riskExists = db.RiskDetails.Where(x => x.RiskAssessmentID == rid && x.RiskID == riskId && x.SubRiskID == subRiskId && x.MitigantID == mitigantId).ToList();
        if (riskExists.Count > 0 && riskExists != null)
        {
          riskModel.Departments = db.DepartmentsMaster.ToList();
          riskModel.Risks = db.RiskMasters.ToList();
          if (riskModel.RiskID > 0)
            riskModel.SubRisks = db.SubRisksMaster.Where(x => x.RiskId == riskModel.RiskID).ToList();
          else
            riskModel.SubRisks = new List<SubRiskMaster>();

          if (riskModel.SubRiskID > 0)
            riskModel.Mitigants = db.MitigantsMaster.Where(x => x.SubRiskId == riskModel.SubRiskID).ToList();
          else
            riskModel.Mitigants = new List<MitigantMaster>();

          riskModel.Shared_process_Departments = db.DepartmentsMaster.ToList();
          ViewBag.RiskDetailsId = riskExists.FirstOrDefault().RiskDetailID;
          ViewBag.RiskExists = "Risk Already Exists";
          return View(riskModel);
        }
        RiskDetailsModel riskDetail = db.RiskDetails.FirstOrDefault(x => x.RiskDetailID == riskModel.RiskDetailID) ??
                                      new RiskDetailsModel();
        //cid = riskModel.CompanyId;
        //did = riskModel.DepartmentID;
        riskDetail.RiskDetailID = riskModel.RiskDetailID;
        riskDetail.RiskAssessmentID = rid;//riskModel.RiskAssessmentId;
        riskDetail.CompanyID = riskModel.CompanyId;
        riskDetail.DepartmentID = riskModel.DepartmentID;
        riskDetail.RiskID = riskModel.RiskID != 0 ? riskModel.RiskID : riskId;
        //riskDetail.RiskID = riskModel.RiskID;
        riskDetail.SubRiskID = riskModel.SubRiskID != 0 ? riskModel.SubRiskID : subRiskId;
        //riskDetail.SubRiskID = riskModel.SubRiskID;
        riskDetail.SubRisk_Impact = riskModel.SubRisk_Impact;
        riskDetail.SubRisk_Likelyhood = riskModel.SubRisk_Likelyhood;
        riskDetail.Inherenet_risk_rating = riskModel.Inherenet_risk_rating;
        riskDetail.MitigantID = riskModel.MitigantID != 0 ? riskModel.MitigantID : mitigantId;
        //riskDetail.MitigantID = riskModel.MitigantID;
        riskDetail.Mitigant_Importance = riskModel.Mitigant_Importance;
        riskDetail.Mitigant_effectiveness = riskModel.Mitigant_effectiveness;
        riskDetail.Mitigant_whyEffective = riskModel.Mitigant_whyEffective;
        riskDetail.Issue = riskModel.Issue;
        riskDetail.Issue_Severity = riskModel.Issue_Severity;
        riskDetail.ActionPlanAvailable = riskModel.ActionPlanAvailable;
        riskDetail.IsThisRiskBeingAccepted = riskModel.IsThisRiskBeingAccepted;
        riskDetail.LossesAssociatedWithThisRisk = riskModel.LossesAssociatedWithThisRisk;
        riskDetail.Losses = riskModel.Losses;
        riskDetail.ActionPlan = riskModel.ActionPlan;
        DateTime targetDate;
        if (DateTime.TryParse(riskModel.TargetDate + "", out  targetDate))
        {

          riskDetail.TargetDate = riskModel.TargetDate.ToString();
        }
        else
        {
          riskDetail.TargetDate = DateTime.Now.ToString();
        }

        riskDetail.ActionPlan_Status = riskModel.ActionPlan_Status;
        riskDetail.Reason_Risk_acceptance = riskModel.Reason_Risk_acceptance;
        riskDetail.List_risk_associated = riskModel.List_risk_associated;
        riskDetail.Owner = riskModel.Owner;
        riskDetail.Shared_process_Department = riskModel.Shared_process_Department;
        riskDetail.Shared_process_Description = riskModel.Shared_process_Description;
        if (riskDetail.RiskDetailID == 0)
        {
          riskDetail.insertedmachineinfo = ip;

Rcsa.Web/Controllers/RiskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rcsa.Web.Models;
using WebMatrix.WebData;

namespace Rcsa.Web.Controllers
{
  [Authorize]
  public class RiskController : Controller
  {
    //
    // GET: /Risk/

    RcsaDb db = new RcsaDb();
    public ActionResult Index()
    {
      return View();
    }

        //
        // GET: /Risk/Details/5
        public ActionResult RiskDetail(string page)
        {
            if (page == null)
            {
                page = null;
            }
            ViewBag.CurrentlyOnPage = page;

            var list = db.RiskMasters.ToList();
            return View(list);
        }

    [HttpPost]
    public ActionResult RiskDetail(string keyword, string command)
    {
      List<RiskMaster> list = new List<RiskMaster>();
      if (keyword != "" && keyword != null)
      {
        list = db.RiskMasters.ToList();
        list = list.Where(x => x.RiskName.Contains(keyword)).ToList();// || x.Description.Contains(keyword)).ToList();
      }
      if (command == "Reset")
      {
        list = db.RiskMasters.ToList();

      }
      ViewBag.Mode = "Search";
      return View(list.OrderBy(x => x.RiskName));

    }

        public ActionResult Details(int id, string page)
        {
            if (page == null)
            {
                page = null;
            }
            ViewBag.CurrentlyOnPage = page;
            RiskMaster list = db.RiskMasters.FirstOrDefault(x => x.RiskId == id);
            return View(list);
            //return View();
        }


        //
        // GET: /Risk/Create

        public ActionResult Create()
    {
      return View();
    }

    //
    // POST: /Risk/Create

    [HttpPost]
    public ActionResult Create(RiskMaster risk)
    {
      try
      {
        bool list = db.RiskMasters.Any(x => x.RiskName == risk.RiskName);
        if (list)
        {
          ViewBag.Error = "Risk name already exist!";
          return View();
        }
        risk.CreatedBy = WebSecurity.CurrentUserId;
        risk.CreatedOn = DateTime.Now;

        db.RiskMasters.Add(risk);
        db.SaveChanges();
        // TODO: Add insert logic here
        return RedirectToAction("RiskDetail");
      }
      catch
      {
        return View();
      }
    }

    //
    // GET: /Risk/Edit/5

    public ActionResult Edit(int id)
    {
      RiskMaster list = db.RiskMasters.FirstOrDefault(x => x.RiskId == id);
      return View(list);
    }

    //
    // POST: /Risk/Edit/5

    [HttpPost]
    public ActionResult Edit(int id, FormCollection collection, RiskMaster risk)
    {
      try
      {
        string page = collection["page"];
        // TODO: Add update logic here
        RiskMaster list = db.RiskMasters.FirstOrDefault(x => x.RiskId == id);
        if (ModelState.IsValid)
        {

          var exists = db.RiskMasters.Any(x => x.RiskName == risk.RiskName && x.RiskId != id);
          if (exists)
          {
            ViewBag.Error = "Risk name already exist!";
            return View();
          }

          if (Request.Form["delete"] != null)
          {
            var list1 = db.RiskMasters.Where(x => x.RiskId == id);
            db.RiskMasters.Remove(list1.First());
            db.SaveChanges();
            return RedirectToAction("RiskDetail", new { page = page });
          }
          list.RiskName = risk.RiskName;
          list.Description = risk.Description;
          list.UpdateBy = WebSecurity.CurrentUserId;
          list.UpdateOn = DateTime.Now;
          //UpdateModel(list);
          db.SaveChanges();
        }
        return RedirectToAction("RiskDetail", new { page = page });
      }
      catch
      {
        return View();
      }
    }

    //
    // GET: /Risk/Delete/5

    public ActionResult Delete(int id, string page)
    {
            if (page == null)
            {
                page = null;
            }
            ViewBag.CurrentlyOnPage = page;
            if (User.IsInRole("Admin") || User.IsInRole("Consultant") || User.IsInRole("Supervisor") || User.IsInRole("Managers"))
            {
                var risk = db.RiskMasters.Where(x => x.RiskId == id);
                if (risk.Any())
                {
                    var rk = risk.FirstOrDefault();
                    var rd = db.RiskDetails.Where(r => r.RiskID == rk.RiskId);

                    foreach(var r in rd)
                    {
                        db.RiskDetails.Remove(r);
                    }
                    db.SaveChanges();
                    db.RiskMasters.Remove(risk.First());
                    db.SaveChanges();
                }
            }
                
      return RedirectToAction("RiskDetail", new { page = page });
      //return View();
    }

    //
    // POST: /Risk/Delete/5

    [HttpPost]
    public ActionResult Delete(int id, FormCollection collection)
    {
      try
      {
        // TODO: Add delete logic here

        return RedirectToAction("Index");
      }
      catch
      {
        return View();
      }
    }



    #region JSON Response Functions

    [HttpGet]
    public JsonResult Risks()
    {
      List<RiskMaster> risks = db.RiskMasters.ToList();
      return Json(risks, JsonRequestBehavior.AllowGet);
    }

    #endregion
  }
}

Rcsa.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Risk and Audit Management System (RAMS)</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <center>
            <!-- HEADER START HERE-->
            <header>
                  &nbsp;
            </header>
            <!-- HEADER ENDS HERE-->
            <div id="wraper">
                @RenderBody()
            </div>
        <div class="clear">&nbsp;</div>
        <div style="margin-top:20px;">
            <!-- Footer start here-->
            <footer >© 2013 Risk and Audit Management System (RAMS). All rights reserved.</footer>
            <!-- Footer Ends here-->
        </div>
            
    </center>
    @RenderSection("scripts", required: false)
    <script>
        $('body').on('click', 'a.del', function () {
            return confirm('Performing this action will delete all the records associated with this item as well. Continue?');
        });
        /*
        $('.del').on('click', function () {
            
        });*/
        </script>
</body>
</html>

Rcsa.Web/Views/Shared/_SubLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var db = new Rcsa.Web.Models.RcsaDb();
    var profile = db.UserProfiles.FirstOrDefault(x => x.UserId == WebSecurity.CurrentUserId);
}

<div class="fix_width">
    <div class="logo_header">
        <div class="logo" style="float: left;">
            <img src="/images/logo.jpg"
                style="max-width: 200px; max-height: 130px; margin-top: 10px; margin-left: 20px; width: 160px; height: 160px" />

        </div>

        <div class="logo_right">

            <div>
                <h1 style="font-size: 20px; margin-top: 20px; margin-right: 120px;">Risk and Audit Management System (RAMS)</h1>
            </div>

            <div style="height: 30px;">
                &nbsp;
            </div>

            <div>
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <span style="font-size: medium; font-weight: bold; font-family: open sans; font-size: 14px;">Welcome 
                <label style="color: #1887bf; font-family: open sans; font-size: 14px;">
                    @User.Identity.Name
                </label>
                    </span> 
            
                    <span style="float: right; padding-right: 10px; color: #1887bf; font-family: open sans; font-size: 13px;">
                        <a href="@Url.Action("Index", "Orm")">
                            <img src="/images/Home.gif" align="absmiddle" />
                            HOME </a>
                            &nbsp;&nbsp;&nbsp;&nbsp; 
                        <a href="@Url.Action("Login", "Account")">
                            <img src="/images/logout.gif" align="absmiddle" />
                            <span style="color: red; font-family: open sans; font-size: 13px;">LOGOUT </span>
                        </a>
                    </span>
                }
            </div>
        </div>
    </div>
</div>
<div class="section1">
    <div class="leftside_box">
        <div class="arrowlistmenu1">
          
                <h3 class="menuheader expandable openheader" headerindex="0h"><span class="accordprefix"></span>Security<span class="accordsuffix"></span></h3>
            
                <ul class="categoryitems" contentindex="0c" style="display: block;">
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a href="@Url.Action("Users", "Security")">Users</a></li>
                        <li><a href="@Url.Action("Roles", "Security")">Roles</a></li>
                    }
                    <li><a href="@Url.Action("Manage", "Account")">Change Password</a></li>
                </ul>
            <h3 class="menuheader expandable" headerindex="1h"><span class="accordprefix"></span>Master Lists<span class="accordsuffix"></span></h3>
            <ul class="categoryitems" contentindex="1c" style="display: none;">
                @if (!User.IsInRole("User") && !User.IsInRole("Manager"))
                {
                    <li><a href="@Url.Action("CompanyDetails", "Company")">Manage Companies</a></li>

                    <li><a href="@Url.Action("ConsultantUsers", "ConsultantUser")">Manage Consultants</a></li>

                }

                @if (!User.IsInRole("User") && (profile.IsCompanyStaff ?? false)
                    && (profile.IsCompanySupervisor ?? false))
                {
                    <li><a href="@Url.Action("DepartmentDetails", "Department")">Manage Departments</a></li>

                }
                @if (User.IsInRole("Consultant") || User.IsInRole("Admin"))
                {
                    {
                        <li><a href="@Url.Action("DepartmentDetails", "Department")">Manage Departments</a></li>

                    }
                }

                @if (User.IsInRole("Admin") || User.IsInRole("Consultant"))
                {
                    <li><a href="@Url.Action("CompanyUser", "CompanyUser")">Manage Company Users</a></li>

                    <li><a href="@Url.Action("UserDepartment", "Security")">Manage Department Users</a></li>
                }
                @if (User.IsInRole("Manager"))
                {
                    <li><a href="@Url.Action("UserDepartment", "Security")">Manage Department Users</a></li>
                }

                @if (User.IsInRole("Admin") || User.IsInRole("Consultant"))
                {
                    <li><a href="@Url.Action("RiskDetail", "Risk")">Manage Risks</a></li>
                    <li><a href="@Url.Action("SubRiskDetails", "SubRisk")">Manage Sub Risks</a></li>
                }


                @if (User.IsInRole("Manager") || User.IsInRole("User"))
                {
                    <li><a href="@Url.Action("MitigantDetails", "Mitigant")">Add Controls/Mitigants</a></li>
                }
                else
                {
                    <li><a href="@Url.Action("MitigantDetails", "Mitigant")">Manage Controls/Mitigants</a></li>
                }
                <li><a href="@Url.Action("DepartmentRisks", "Orm")">Risk Identification /Risk Assessments</a></li>
                <li><a href="@Url.Action("ViewRisks", "Orm")">View Risk Already Assessed</a></li>
                @*<li><a href="@Url.Action("UpdateRisk", "Orm")">Update Risk Assessment</a></li>*@
            </ul>
            <h3 class="menuheader expandable" headerindex="2h"><span class="accordprefix"></span>Reports<span class="accordsuffix"></span></h3>
            <ul class="categoryitems" contentindex="2c" style="display: none;">
                @*    <li><a href="@Url.Action("UsersReport", "CompanyUsersReport")">Department Report</a></li>*@
                @*<li><a href="@Url.Action("CustomizedReport", "CompanyUsersReport")">Customized Report 2</a></li>*@
                @*   <li><a href="@Url.Action("BoardReports", "BoardReport")">Board Report</a></li>*@
                @*   <li><a href="@Url.Action("StandardReports", "Standard")">Specific Risk Type Report</a></li>*@
                <li><a href="@Url.Action("DepartmentRisks", "Standard")">Department Report</a></li>
                <li><a href="@Url.Action("BoardRisk", "Standard")">Board Report</a></li>
                <li><a href="@Url.Action("SpecificTypeRisk", "Standard")">Specific Risk Type Report</a></li>
                <li><a href="@Url.Action("Index", "HeatMap")">Heat Map Report</a></li>

            </ul>
        </div>
    </div>
    <div class="middle_box">
        <div class="middle_innerbox">
            @RenderBody()
        </div>
    </div>
</div>

<script type="text/javascript" src="/scripts/ddaccordion.js"></script>

@section scripts
{
    <script type="text/javascript">

        ddaccordion.init({
            //top level headers initialization
            headerclass: "expandable", //Shared CSS class name of headers group that are expandable
            contentclass: "categoryitems", //Shared CSS class name of contents group
            revealtype: "click", //Reveal content when user clicks or onmouseover the header? Valid value: "click", "clickgo", or "mouseover"
            mouseoverdelay: 200, //if revealtype="mouseover", set delay in milliseconds before header expands onMouseover
            collapseprev: true, //Collapse previous content (so only one open at any time)? true/false 
            defaultexpanded: [0], //index of content(s) open by default [index1, index2, etc]. [] denotes no content
            onemustopen: false, //Specify whether at least one header should be open always (so never all headers closed)
            animatedefault: false, //Should contents open by default be animated into view?
            persiststate: true, //persist state of opened contents within browser session?
            toggleclass: ["", "openheader"], //Two CSS classes to be applied to the header when it's collapsed and expanded, respectively ["class1", "class2"]
            togglehtml: ["prefix", "", ""], //Additional HTML added to the header when it's collapsed and expanded, respectively  ["position", "html1", "html2"] (see docs)
            animatespeed: "fast", //speed of animation: integer in milliseconds (ie: 200), or keywords "fast", "normal", or "slow"
            oninit: function (headers, expandedindices) { //custom code to run when headers have initalized
                //do nothing
            },
            onopenclose: function (header, index, state, isuseractivated) { //custom code to run whenever a header is opened or closed
                //do nothing
            }
        });

        ddaccordion.init({
            //2nd level headers initialization
            headerclass: "subexpandable", //Shared CSS class name of sub headers group that are expandable
            contentclass: "subcategoryitems", //Shared CSS class name of sub contents group
            revealtype: "click", //Reveal content when user clicks or onmouseover the header? Valid value: "click" or "mouseover
            mouseoverdelay: 200, //if revealtype="mouseover", set delay in milliseconds before header expands onMouseover
            collapseprev: true, //Collapse previous content (so only one open at any time)? true/false 
            defaultexpanded: [], //index of content(s) open by default [index1, index2, etc]. [] denotes no content
            onemustopen: false, //Specify whether at least one header should be open always (so never all headers closed)
            animatedefault: false, //Should contents open by default be animated into view?
            persiststate: true, //persist state of opened contents within browser session?
            toggleclass: ["opensubheader", "closedsubheader"], //Two CSS classes to be applied to the header when it's collapsed and expanded, respectively ["class1", "class2"]
            togglehtml: ["none", "", ""], //Additional HTML added to the header when it's collapsed and expanded, respectively  ["position", "html1", "html2"] (see docs)
            animatespeed: "fast", //speed of animation: integer in milliseconds (ie: 200), or keywords "fast", "normal", or "slow"
            oninit: function (headers, expandedindices) { //custom code to run when headers have initalized
                //do nothing
            },
            onopenclose: function (header, index, state, isuseractivated) { //custom code to run whenever a header is opened or closed
                //do nothing
            }
        });

    </script>

}

@RenderSection("scripts", required: false)