Rcsa.Web/Models/UserDepartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Rcsa.Web.Models
{
  [Table("UserDepartment")]
  public class UserDepartment
  {
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int UserDepartmentId { get; set; }

    [ForeignKey("UsersProfile")]
    public int UserId { get; set; }
    [ForeignKey("UserId")]
    public virtual UserProfile UsersProfile { get; set; }

    [ForeignKey("DepartmentMasters")]
    public int DepartmentId { get; set; }
    [ForeignKey("DepartmentId")]
    public virtual DepartmentMaster DepartmentMasters { get; set; }


    //[ForeignKey("CompaniesMasters")]
    public int CompanyId { get; set; }
    //[ForeignKey("CompanyId")]
    //public virtual CompanyMaster CompaniesMasters { get; set; }

  }
}

Rcsa.Web/Controllers/SecurityController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using Rcsa.Web.Models;
using WebMatrix.WebData;
using System.Collections.Generic;

using System.Web;
using Rcsa.Web.ViewModel;
//using System.Web.Security;
//using Rcsa.Web.Models;
//using WebMatrix.WebData;

namespace Rcsa.Web.Controllers
{
  [Authorize]
  public class SecurityController : Controller
  {
    RcsaDb db = new RcsaDb();
    public ActionResult Users()
    {
      var users = db.UserProfiles.OrderBy(x => x.FirstName);
      return View(users.ToList());
    }

    public ActionResult ChangePassword(int userId)
    {
      ViewBag.UserId = userId;
      return View();
    }

    [HttpPost]
    public ActionResult ChangePassword(LocalResetPasswordModel model)
    {
      int userId;
      int.TryParse(Request.Form["hdUserId"], out userId);
      if (ModelState.IsValid)
      {
        bool changePasswordSucceeded;
        try
        {
          var userName = db.UserProfiles.FirstOrDefault(x => x.UserId == userId).UserName;
          var token = WebSecurity.GeneratePasswordResetToken(userName);
          var result = WebSecurity.ResetPassword(token, model.NewPassword);
          changePasswordSucceeded = true;
        }
        catch (Exception ex)
        {
          changePasswordSucceeded = false;
        }

        if (changePasswordSucceeded)
        {
          ViewBag.Message = "Password changed successfully";
        }
        else
        {
          ModelState.AddModelError("", "The current password is incorrect or the new password is invalid.");
        }
      }

      ViewBag.UserId = userId;
      return View();
    }

    [HttpPost]
    public ActionResult Users(string keyword, string command)
    {
      var userList = new List<UserProfile>();
      if (keyword != "" && keyword != null)
      {
        userList = db.UserProfiles.Where(x => x.UserName.Contains(keyword) ||
                           x.FirstName.Contains(keyword) || x.LastName.Contains(keyword) || x.Email.Contains(keyword)).ToList();
      }
      if (command == "Reset")
      {
        userList = db.UserProfiles.OrderBy(x => x.FirstName).ToList();
      }
      ViewBag.Mode = "Search";
      return View(userList);
    }

    public ActionResult UsersEdit(int userId)
    {
      var q = db.UserProfiles.Where(x => x.UserId == userId);
      var user = q.Any() ? q.First() : new UserProfile();
      return View(user);
    }

    [HttpPost]
    public ActionResult UsersEdit(UserProfile model, string isActive)
    {
      try
      {
        if (!String.IsNullOrWhiteSpace(model.UserName) && WebSecurity.UserExists(model.UserName) && model.UserId == 0)
        {
          ModelState.AddModelError("", "User name already exist!");
          return View(model);
        }

        var user = db.UserProfiles.Where(x => x.Email == model.Email && x.UserId != model.UserId);
        if (user.Any())
        {
          ModelState.AddModelError("", "Email already exist!");
          return View(model);
        }

        var q = db.UserProfiles.Where(x => x.UserId == model.UserId);
        var newUser = q.Any() ? q.First() : new UserProfile();

        model.IsActive = newUser.IsActive = !String.IsNullOrWhiteSpace(isActive);
        newUser.FirstName = model.FirstName;
        newUser.LastName = model.LastName;
        newUser.Email = model.Email;
        newUser.UpdateOn = DateTime.Now;
        newUser.UpdateBy = WebSecurity.CurrentUserId;

        ////newUser.UpdateBy =
        //if (newUser.UserId == 0)
        //{
        //  db.UserProfiles.Add(newUser);
        //}

        db.SaveChanges();
        foreach (string roleName in System.Web.Security.Roles.GetRolesForUser(model.UserName))
        {
          System.Web.Security.Roles.RemoveUserFromRole(model.UserName, roleName);
        }

        //Remove from company if any assigned
        CompanyViewModel.RemoveFromCompany(model.UserId);

        if (!String.IsNullOrWhiteSpace(Request.Form["Role"] + ""))
        {
          var roleName = Request.Form["Role"] + "";
          System.Web.Security.Roles.AddUsersToRole(new[] { model.UserName }, roleName);
          //Assing company if in company role
          if (roleName.Equals("Manager", StringComparison.InvariantCultureIgnoreCase) || roleName.Equals("User", StringComparison.InvariantCultureIgnoreCase))
          {
            var companyId = Request.Form["dlCompany"] + "";
            if (!String.IsNullOrWhiteSpace(companyId))
            {
              CompanyViewModel.AssignCompany(model.UserId, Convert.ToInt32(companyId));
            }
          }
        }


        ViewBag.Status = "User updated successfully!";
      }
      catch (MembershipCreateUserException e)
      {
        ModelState.AddModelError("", ErrorCodeToString(e.StatusCode));
      }

      return View(model);
    }

    public ActionResult UsersAdd()
    {
      return View();
    }
    [HttpPost]
    public ActionResult UsersAdd(RegisterModel model)
    {
      if (ModelState.IsValid)
      {
        // Attempt to register the user
        try
        {
          //Check if user already exist 
          if (WebSecurity.UserExists(model.UserName))
          {
            ModelState.AddModelError("", "User name already exist!");
            return View(model);
          }

          var user = db.UserProfiles.Where(x => x.Email == model.Email);
          if (user.Any())
          {
            ModelState.AddModelError("", "Email already exist!");
            return View(model);
          }

          //Check if email id already exist

          string confirmationToken =
            WebSecurity.CreateUserAndAccount(model.UserName, model.Password,
                                             new
                                             {
                                               FirstName = model.FirstName,
                                               LastName = model.LastName,
                                               Email = model.Email,
                                               IsActive=true
                                             },
                                             true);


          bool result = WebSecurity.ConfirmAccount(confirmationToken);


          if (result)
          {
            var profile = db.UserProfiles.FirstOrDefault(x => x.UserName == model.UserName);
            if (profile != null)
            {
              var roleName = Request.Form["dlRole"] + "";
              if (!String.IsNullOrWhiteSpace(roleName))
              {
                System.Web.Security.Roles.AddUsersToRole(new[] { model.UserName }, roleName);
                //Assign company if in company role
                if (roleName.Equals("Manager", StringComparison.InvariantCultureIgnoreCase) || roleName.Equals("User", StringComparison.InvariantCultureIgnoreCase))
                {
                    var companyId = Request.Form["dlCompany"] + "";
                    if (!String.IsNullOrWhiteSpace(companyId))
                    {
                        CompanyViewModel.AssignCompany(profile.UserId, Convert.ToInt32(companyId));
                    }
                }
              }

              return RedirectToAction("Users");
            }
          }
        }
        catch (MembershipCreateUserException e)
        {
          ModelState.AddModelError("", ErrorCodeToString(e.StatusCode));
        }
      }

      // If we got this far, something failed, redisplay form
      return View(model);
    }

    public ActionResult UsersRole()
    {
      //var role = Roles.Provider;

      //Roles.GetUsersInRole("admin");
      //return View();

      var role = System.Web.Security.Roles.GetRolesForUser().Single();
      var users = db.UserProfiles.OrderBy(x => x.FirstName);
      return View(users.ToList());
    }

    [HttpPost]
    public ActionResult UsersRole(UserProfile model)
    {
      try
      {
        string userName = "", roleName = "";
        int userId = 0, newEdit = 0;
        if (Request["hfNewEdit"] != null && Request["hfNewEdit"].ToString().Length > 0)
          newEdit = Convert.ToInt32(Request["hfNewEdit"]);
        if (Request["ddlUser"] != null && Request["ddlUser"].ToString().Length > 0)
          userId = Convert.ToInt32(Request["ddlUser"]);
        if (Request["ddlRole"] != null && Request["ddlRole"].ToString().Length > 0)
          roleName = Request["ddlRole"].ToString();
        if (userId > 0)
        {
          var user = db.UserProfiles.FirstOrDefault(x => x.UserId == userId);
          string[] role = System.Web.Security.Roles.GetRolesForUser(user.UserName);
          if (newEdit == 0)
          {
            if (role.Length > 0)
            {
              ViewBag.Status = "Role Already Exists!";
              //ModelState.AddModelError("", "Role Already Define");
              return RedirectToAction("UsersRole");

            }
            System.Web.Security.Roles.AddUsersToRole(new[] { user.UserName }, roleName);
          }
          else if (newEdit == 1)
          {
            if (role.Length > 0)
            {
              System.Web.Security.Roles.RemoveUserFromRole(user.UserName, role[0]);
            }
            System.Web.Security.Roles.AddUsersToRole(new[] { user.UserName }, roleName);
          }
        }
        //return View();
        return RedirectToAction("UsersRole");
      }
      catch (Exception ex)
      {
        return RedirectToAction("UsersRole");
      }
    }

    public ActionResult UserDetail(int userId)
    {
      var q = db.UserProfiles.Where(x => x.UserId == userId);
      var user = q.Any() ? q.First() : new UserProfile();
      return View(user);
    }


Rcsa.Web/Views/Security/ChangePassword.cshtml
@model Rcsa.Web.Models.LocalResetPasswordModel
@{
    ViewBag.Title = "Change Password";
    Layout = "~/Views/Shared/_SubLayout.cshtml";
}
<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center;">Change User password</h3>
<div class="form1">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()    
    <input type="hidden" value="@ViewBag.UserId" name="hdUserId" id="hdUserId" />    
        <fieldset>           
            @Html.LabelFor(m => m.NewPassword)
            @Html.PasswordFor(m => m.NewPassword)
            <div class="clear"></div>
            @Html.LabelFor(m => m.ConfirmPassword)
            @Html.PasswordFor(m => m.ConfirmPassword)
            <div class="clear"></div>
            <label></label>
            <input type="submit" class="button1" value="Change password" style="width:150px" />
            
        </fieldset>
    <div class="clear"></div>            
            if(!String.IsNullOrWhiteSpace(ViewBag.Message ))
            {
                <div class="success">@ViewBag.Message</div>
            }
}
</div>



Rcsa.Web/Views/Security/Roles.cshtml
@{
    ViewBag.Title = "Roles";
    Layout = "~/Views/Shared/_SubLayout.cshtml";
}

<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center;">Roles</h3>
<table id="hor-minimalist-b" >
    <thead>
    	<tr>
        	<th scope="col">Role Id</th>
	        <th scope="col">Role Name</th>
	        <th scope="col">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @{ int i = 0;}
        @foreach (var item in Roles.GetAllRoles())
        {
            i++;
            <tr>
                <td>@i</td>
                <td>@item</td>
                <td>@*<a href="#">Edit</a> | <a href="#">Delete</a>*@</td>
            </tr>
        }
    </tbody>
</table>

Rcsa.Web/Views/Security/RolesModule.cshtml
@{
    ViewBag.Title = "RolesEdit";
    Layout = "~/Views/Shared/_SubLayout.cshtml";
}

<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center;">Roles Module</h3>

Rcsa.Web/Views/Security/UserDetail.cshtml
@model Rcsa.Web.Models.UserProfile

@{
    Rcsa.Web.Models.RcsaDb db = new Rcsa.Web.Models.RcsaDb();
    var companyUser = db.CompanyUsers.FirstOrDefault(x => x.UserId == Model.UserId);
    string CompanyName = "";
    if(companyUser!=null)
    {
        var company = db.CompaniesMaster.Where(x => x.CompanyId == companyUser.CompanyId).SingleOrDefault();
        CompanyName = company.ComapnyName;
    }
    ViewBag.Title = "User Detail";
    Layout = "~/Views/Shared/_SubLayout.cshtml";    
}

<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center;">User Details</h3>
<div class="form1" style="text-align: left; margin-left: 20px">
     <table id="hor-minimalist-b" style="margin: 7px 10px 62px -20px;line-height:5px;" >
    <tbody >
        <tr>
            <td style="width:216px;">
                <label>User Id </label>
            </td>
           <td>@Model.UserName</td>
            
        </tr>

         <tr>
            <td>
              <label>User Name </label>
            </td>
            <td>
                @Model.UserName
            </td>
            
        </tr>


         <tr>
            <td>
                <label>Name </label>
            </td>
            <td>
                 @Model.FirstName @Model.LastName
            </td>
            
        </tr>


         <tr>
            <td>
                 <label>Email</label>
            </td>
            <td>
                @Model.Email
            </td>
            
        </tr>


         <tr>
            <td>
                <label>Company Name </label>
            </td>
            <td>
                @CompanyName
            </td>
            
        </tr>


       
       
       

</tbody></table>


</div>
<div style="float:right;clear:both;margin-bottom:20px;margin-right:40px;text-decoration:underline;">
    <b>@Html.ActionLink("Return to List", "Users", "Security")</b>
</div>


Rcsa.Web/Views/Security/Users.cshtml
@model IList<Rcsa.Web.Models.UserProfile>
@{
    Layout = "~/Views/Shared/_SubLayout.cshtml";
    ViewBag.Title = "Users";    
}

<link href="~/Content/grid.css" rel="stylesheet" />
<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center;">Users</h3>

@using (Html.BeginForm())
{    
    <div class="searchBoxDiv">
        <span style="float: left">
            <input type="text" id="txtSearch" value="" name="keyword" placeholder="Search" style="width: 282px; margin-left: -23px;" />
            <input type="submit" value="Search" id="btnSearch" class="searchButton" />
            <input type="submit" value="Reset" id="btnReset" name="command" class="searchButton" />
        </span>
        <span style="float: right; margin-top: 6px; margin-right: 18px;"><strong><u>@Html.ActionLink("Add User", "UsersAdd", "Security")</u></strong></span>
    </div>
    <div style="height: 25px;"></div>            
}
<table class="minilist-b">
    <tr>
        <td>
            <div id="dvGrid">
                @if (Model.Count > 0)
                {
                    var gridTest = new WebGrid(Model, canPage: true, canSort: true, defaultSort: "UserName", rowsPerPage: 10, ajaxUpdateContainerId: "dvGrid");                    
                    @gridTest.GetHtml(
                tableStyle: "mGrid",
                alternatingRowStyle: "mGrid-alternating-row",
                          footerStyle: "pagination",
                          mode: WebGridPagerModes.All,
                          numericLinksCount: 10,
                          firstText: "First",
                          lastText: "Last",
                          previousText: "Prev",
                          nextText: "Next",
                columns: new[] {                  
                    gridTest.Column("UserName",header: "User Name"),
                    gridTest.Column("FirstName",header: "Name",format: (item) => (item.FirstName == null ? "" :item.FirstName )+' '+ (item.LastName == null ? "" :item.LastName )),
                    gridTest.Column("Email",header: "Email"),                                        
                    gridTest.Column("isActive",header: "Active", format: (item) => item.IsActive ?? false),    
                    gridTest.Column("",header:"",style: "grd-action",
                    format: @<text>
                    <div>
                        @Html.ActionLink("Edit", "UsersEdit", new { userId = item.UserId }) | 
                        @Html.ActionLink("Details", "UserDetail", new { userId = item.UserId }) |
                        @Html.ActionLink("Change Password", "ChangePassword", new { userId = item.UserId }) 

                    </div>
                    </text>
                    )
                })
                }
            </div>
            @if (@ViewBag.Mode == "Search" && Model.Count() == 0)
            {
                <div id="error" class="error" style="width: 747px;">No records found!!!</div>
            }            
        </td>
    </tr>

</table>

Rcsa.Web/Views/Security/UsersAdd.cshtml
@using Rcsa.Web.ViewModel
@model Rcsa.Web.Models.RegisterModel
@{
    ViewBag.Title = "UsersAdd";
    Layout = "~/Views/Shared/_SubLayout.cshtml";
}

<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center;">Add User</h3>

<div class="form1">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <fieldset>

            <label>User Name <span class="requiredFields">*</span></label>
            @Html.TextBoxFor(m => m.UserName, new { placeholder = "User name", autofocus = "", @MaxLength = "15" })
            <div class="clear"></div>
            <div class="clear"></div>
            <label>First Name <span class="requiredFields">*</span></label>
            @Html.TextBoxFor(m => m.FirstName, new { placeholder = "First name", autofocus = "", @MaxLength = "20" })
            <div class="clear"></div>
            <label>Last Name <span class="requiredFields">*</span></label>
            @Html.TextBoxFor(m => m.LastName, new { placeholder = "Last name", autofocus = "", @MaxLength = "20" })
            <div class="clear"></div>
            <label>Email <span class="requiredFields">*</span></label>
            @Html.TextBoxFor(m => m.Email, new { placeholder = "Email", autofocus = "", autocomplete = "off", @MaxLength = "50" })
            <div class="clear"></div>
            <label>Roles</label>
            @Html.DropDownList("dlRole", new SelectList(Roles.GetAllRoles().ToList()), "--- Select ---", new { id = "dlRole", style = "width:348px;height:36px;" })
            <div class="clear"></div>
            <div id="divCompany" style="display: none">
                <label>Company</label>
                @Html.DropDownList("dlCompany", new SelectList(CompanyViewModel.GetAllCompany(), "CompanyId", "ComapnyName"), "--- Select ---", new { id = "dlCompany", style = "width:348px;height:36px;" })
                <div class="clear"></div>
            </div>
            <label>Password <span class="requiredFields">*</span></label>
            @Html.PasswordFor(m => m.Password, new { placeholder = "Password", autofocus = "", @MaxLength = "12" })
            <div class="clear"></div>
            <label>Re-Password <span class="requiredFields">*</span></label>
            @Html.PasswordFor(m => m.ConfirmPassword, new { placeholder = "Re Password", autofocus = "", @MaxLength = "12" })
            <div class="clear"></div>
            <br />
            <label>&nbsp;</label>
            <div>
                <button id="btnSave" value="Save" class="button2">Save</button>
                &nbsp;&nbsp;
            <button id="btnReset" value="Reset" type="reset" class="button2">Reset</button>
            </div>
        </fieldset>
    }
</div>
@section scripts
{
    <script>
        $(document).ready(function () {

            $("#dlRole").change(function () {
                showCompany($(this).val());
            });

            function showCompany(values) {
                if (values == "User" || values == "Manager") {
                    $("#divCompany").show();
                } else {
                    $("#divCompany").hide();
                }
            }

            $("#btnSave").click(function () {
                if ($("#dlRole option:selected").val() == "User" || $("#dlRole option:selected").val() == "Manager") {
                    if ($("#dlCompany option:selected").val() == "" || $("#dlCompany option:selected").val() == undefined) {
                        alert("You have not selected a Company for this User.");
                        return false;
                    }
                }
                return true;
            });

        });

        
    </script>
}

Rcsa.Web/Views/Security/UsersRole.cshtml
@using Rcsa.Web.Models
@model IList<Rcsa.Web.Models.UserProfile>
@{
    var _entities = new Rcsa.Web.Models.RcsaDb();
    RcsaDb db = new RcsaDb();
    ViewBag.Title = "UsersRole";
    Layout = "~/Views/Shared/_SubLayout.cshtml";
    string[] users = Roles.GetUsersInRole("Company");
    //var role = Roles.GetAllRoles().ToList();

    string role = System.Web.Security.Roles.GetRolesForUser().Single();
    var selectedUser = Roles.GetUsersInRole(role);
}

<script type="text/javascript">
    function ConfirmEdit(user, role) {
        ClearControls();
        document.getElementById('hfNewEdit').value = 1;
        document.getElementById('ddlUser').value = user;
        document.getElementById('ddlRole').value = role;
        $('#dvRoleAssign').slideDown('slow');
        document.getElementById('btnNew').style.display = 'none';
        return false;
    }
    function showNew() {
        ClearControls();
        $('#dvRoleAssign').slideDown('slow');
        document.getElementById('btnNew').style.display = 'none';
        return false;
    }
    function Reset() {
        $('#dvRoleAssign').slideUp('slow');
        document.getElementById('btnNew').style.display = '';
        ClearControls();
        return false;
    }
    function ClearControls() {
        document.getElementById('ddlUser').value = "";
        document.getElementById('ddlRole').value = "";
        document.getElementById('hfNewEdit').value = 0;
        //document.getElementById('txtDepartment').value = "";
        //document.getElementById('lblMsg').innerHTML = "";
        //document.getElementById('lblErrorMsg').innerHTML = "";
        return false;
    }
</script>
<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center;">Users Role</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <input type="hidden" runat="server" value="0" id="hfNewEdit" name="hfNewEdit" />
    <div id="dvRoleAssign" style="display: none;">
        <table width="60%">
            <tr>
                <td><strong>User</strong></td>
                <td>
                    @Html.DropDownList("ddlUser", new SelectList(db.UserProfiles.Where(x=> x.UserName.ToLower() != "admin"), "UserId", "UserName"), "---Select---", new { id = "ddlUser", style = "width: 150px;" })
                    @*@Html.DropDownList("ddlUser", new SelectList(Roles.GetUsersInRole(role), "", ""), "---Select---", new { id = "ddlUser", style = "width: 150px;" })*@
                </td>
                <td><strong>Role</strong></td>
                <td>@Html.DropDownList("ddlRole", new SelectList(Roles.GetAllRoles().Where(x => x != "Admin")), "---Select---", new { id = "ddlRole", style = "width: 150px;" })</td>
            </tr>
            <tr>
                <td colspan="3">&nbsp;
                </td>
                <td align="left">
                    <button id="btnSave" value="Save" class="button2">Save</button>
                    <button id="btnReset" value="Reset" class="button2" onclick="javascript:return Reset();">Reset</button>
                </td>
            </tr>
        </table>
    </div>
    <table id="hor-minimalist-b">
        <thead>
            <tr>
                <th scope="col">User Name</th>
                <th scope="col">Name</th>
                <th scope="col">Role Name</th>
                @*<th scope="col">&nbsp;</th>*@
                <th scope="col" style="width: 110px;"><strong><u>@Html.ActionLink("Add User Role", "", "", new { onclick = "return showNew();", id = "btnNew" })</u></strong></th>
            </tr>
        </thead>
        @if (Model != null && Model.Count > 0)
        {

            @*foreach (var item in selectedUser)
            {
                string[] roles = Roles.GetRolesForUser(@item);
                if (roles.Length > 0 && item != "admin")
                {
            <tr>
                <td>
                    @item
                </td>
                <td>
                </td>
                <td>
                    @roles[0].ToString()
                </td>
                <td>
                    @Html.ActionLink("Edit", "", "", new { onclick = "return ConfirmEdit('" + item + "','" + roles[0].ToString() + "');" })
                </td>
            </tr>
                }
            }*@


            foreach (var item in Model)
            {
                string[] roles = Roles.GetRolesForUser(@item.UserName);
                if (roles.Length > 0 && item.UserName != "admin")
                {
            <tr>
                <td>
                    @item.UserName
                </td>
                <td>
                    @item.FirstName  @item.LastName
                </td>
                <td>
                    @roles[0].ToString()
                </td>
                @*<td>
                    @item.Email
                </td>*@
                <td>
                    @Html.ActionLink("Edit", "", "", new { onclick = "return ConfirmEdit('" + item.UserId + "','" + roles[0].ToString() + "');" })
                </td>
            </tr>
                }
            }
        }
    </table>
    
    <div class="clear"></div>
        if (ViewBag.Status != null)
        {
    <div class="success">
        @ViewBag.Status
    </div>
        }
}
@*@using (Html.BeginForm("UsersRole", "Security", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <fieldset>
            <label>User Name</label>
             @Html.DropDownListFor(m => m.UserName, new SelectList(_entities.UserProfiles.ToList(), "UserId", "UserName"), "---Select---", new { id = "UserId"})                             
            <div class="clear"></div>
            <div class="userRoles">
                <span>
                    <fieldset>
                        @Html.CheckBoxFor(m => m.IsPaid)
                        <label>Paid</label>
                        @Html.CheckBoxFor(m => m.IsApproved)
                        <label>Approvals</label>
                        @Html.CheckBoxFor(m => m.IsApproved)
                        <label>Consultant</label>
                    </fieldset>
                </span>
            </div>
            <br />
            <label>&nbsp;</label>
            <button id="btnSave" value="Save" class="button1">Save</button>
            &nbsp;&nbsp;
            <button id="btnReset" value="Reset" type="reset" class="button1">Reset</button>
        </fieldset>
        <div class="clear"></div>
}*@