Rcsa.Web/Controllers/MitigantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Rcsa.Web.Models;
using WebMatrix.WebData;

namespace Rcsa.Web.Controllers
{
  [Authorize]
  public class MitigantController : Controller
  {
    //
    // GET: /Mitigant/

    RcsaDb db = new RcsaDb();
    public ActionResult MitigantDetails(string page)
    {
            if (page == null)
            {
                page = null;
            }
            ViewBag.CurrentlyOnPage = page;
            var list = new List<MitigantMaster>();
            if (User.IsInRole("Admin") || User.IsInRole("Consultant"))
            {
                list = db.MitigantsMaster.ToList();
            }
            else
            {
                var adminConsultantUsers = new List<string>();
                var ids = new List<int>();
                adminConsultantUsers.AddRange(Roles.GetUsersInRole("Admin"));
                adminConsultantUsers.AddRange(Roles.GetUsersInRole("Consultant"));
                ids = db.UserProfiles.Where(x => adminConsultantUsers.Contains(x.UserName)).Select(x => x.UserId).ToList();
                var currentComp = db.CompanyUsers.Where(x => x.UserId == WebSecurity.CurrentUserId).Select(x => x.CompanyId).FirstOrDefault();
                var companyUsers = db.CompanyUsers.Where(x => x.CompanyId == currentComp).Select(x => x.UserId).ToList();
                //var list = db.RiskMasters.OrderByDescending(x => x.CreatedOn).ToList();
                list = db.MitigantsMaster.Where(x => companyUsers.Contains((int)x.InsertedBy) || x.InsertedBy == 1 || ids.Contains((int)x.InsertedBy)).ToList();
            }
            
      return View(list);
    }

    [HttpPost]
    public ActionResult MitigantDetails(string keyword, string command)
    {
      var list = new List<MitigantMaster>();
            if (User.IsInRole("Admin") || User.IsInRole("Consultant"))
            {
                if (!String.IsNullOrEmpty(keyword))
                {
                    list = db.MitigantsMaster.Where(x => x.MitigantName.Contains(keyword)).ToList();
                }
                if (command == "Reset")
                {
                    list = db.MitigantsMaster.ToList();
                }
                ViewBag.Mode = "Search";
            }
            else
            {
            var currentComp = db.CompanyUsers.Where(x => x.UserId == WebSecurity.CurrentUserId).Select(x => x.CompanyId).FirstOrDefault();
            var companyUsers = db.CompanyUsers.Where(x => x.CompanyId == currentComp).Select(x => x.UserId).ToList();
                var adminConsultantUsers = new List<string>();
                var ids = new List<int>();
                adminConsultantUsers.AddRange(Roles.GetUsersInRole("Admin"));
                adminConsultantUsers.AddRange(Roles.GetUsersInRole("Consultant"));
                ids = db.UserProfiles.Where(x => adminConsultantUsers.Contains(x.UserName)).Select(x => x.UserId).ToList();
                if (!String.IsNullOrEmpty(keyword))
              {
                list = db.MitigantsMaster.Where(x => (companyUsers.Contains((int)x.InsertedBy) || x.InsertedBy == 1 || ids.Contains((int)x.InsertedBy)) && x.MitigantName.Contains(keyword)).ToList();
              }
              if (command == "Reset")
              {
                list = db.MitigantsMaster.Where(x => companyUsers.Contains((int)x.InsertedBy) || x.InsertedBy == 1 || ids.Contains((int)x.InsertedBy)).ToList();
              }
              ViewBag.Mode = "Search";
            }

      return View(list.OrderBy(x => x.MitigantName));
    }
    //
    // GET: /Mitigant/Details/5

    public ActionResult Details(int id, string page)
    {
            if (page == null)
            {
                page = null;
            }
            ViewBag.CurrentlyOnPage = page;

            var mitigant = db.MitigantsMaster.FirstOrDefault(x => x.MitigantId == id);
      return View(mitigant ?? new MitigantMaster());
    }

    //
    // GET: /Mitigant/Create

    public ActionResult Create()
    {
      return View();
    }

    //
    // POST: /Mitigant/Create


    public bool IsExist(string mitigantName, int id = 0)
    {
      if (id == 0)
        return db.MitigantsMaster.Any(x => x.MitigantName == mitigantName);
      else
        return db.MitigantsMaster.Any(x => x.MitigantName == mitigantName && x.SubRiskId == id);
    }

    public bool IsExist(string mitigantName, int subRiskId = 0, int id = 0)
    {
      if (id == 0)
        return db.MitigantsMaster.Any(x => x.MitigantName == mitigantName);
      else
        return db.MitigantsMaster.Any(x => x.MitigantName == mitigantName && x.SubRiskId == subRiskId && x.MitigantId != id);
    }



    [HttpPost]
    public ActionResult Create(MitigantMaster mitigant)
    {
      try
      {
        var riskid = Request["ddlRisk"] + "";

        ViewBag.SubRiskSelected = mitigant.SubRiskId + "";
        ViewBag.RiskSelected = riskid;
        ViewBag.MitigantSelected = mitigant.MitigantId + "";
        //  ViewBag.SubRiskSelected = mitigant.SubRiskId + "";

        if (IsExist(mitigant.MitigantName.Trim(), mitigant.SubRiskId))
        {
          ViewBag.Error = "Mitigant name is already exist!";
          return View();
        }

        string ip = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
        if (String.IsNullOrWhiteSpace(ip))
        {
          ip = Request.ServerVariables["REMOTE_ADDR"];
        }
        mitigant.InsertedBy = WebSecurity.CurrentUserId;
        mitigant.Insertedon = DateTime.Now;
        mitigant.Insertedmachineinfo = ip;
        db.MitigantsMaster.Add(mitigant);
        db.SaveChanges();

        return RedirectToAction("MitigantDetails");
      }
      catch
      {
        return View();
      }
    }

    //
    // GET: /Mitigant/Edit/5

    public ActionResult Edit(int id)
    {
      MitigantMaster list = db.MitigantsMaster.Where(x => x.MitigantId == id).SingleOrDefault();
      return View(list);
    }

    //
    // POST: /Mitigant/Edit/5

    [HttpPost]
    public ActionResult Edit(int id, FormCollection collection, MitigantMaster objMitigant)
    {
      string ip = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
      if (String.IsNullOrWhiteSpace(ip))
      {
        ip = Request.ServerVariables["REMOTE_ADDR"];
      }
      try
      {
                string page = collection["page"];
        MitigantMaster list = db.MitigantsMaster.Where(x => x.MitigantId == id).SingleOrDefault();
        list.MitigantName = objMitigant.MitigantName;
        list.SubRiskId = objMitigant.SubRiskId;
        list.MitigantDesc = objMitigant.MitigantDesc;
        list.Updatedby = WebSecurity.CurrentUserId;
        list.Updatedon = DateTime.Now;
        list.Updatemachineinfo = ip;
        if (ModelState.IsValid)
        {
          if (objMitigant.SubRiskId != null && objMitigant.MitigantName != null)
          {
            if (IsExist(list.MitigantName.Trim(), list.SubRiskId, list.MitigantId))
            {
              // ViewBag.Error = "Mitigant name is already exist!";
              return RedirectToAction("MitigantDetails", new { page = page });
            }

            //UpdateModel(list);
            db.SaveChanges();

            return RedirectToAction("MitigantDetails", new { page = page });
          }
          else
          {
            ModelState.AddModelError("", "Name is required!");
            return View(objMitigant);
          }
        }
        else
        {

          return RedirectToAction("MitigantDetails", new { page = page });

        }
      }
      catch
      {
        return View(objMitigant);
      }
    }

        //
        // GET: /Mitigant/Delete/5

        public ActionResult Delete(int id, string page)
        {
            if (page == null)
            {
                page = null;
            }
            ViewBag.CurrentlyOnPage = page;
            if (User.IsInRole("Admin") || User.IsInRole("Consultant") || User.IsInRole("Supervisor") || User.IsInRole("Managers"))
            {
                var mitigant = db.MitigantsMaster.Where(x => x.MitigantId == id);
                if (mitigant.Any())
                {
                    var mt = mitigant.FirstOrDefault();
                    var rd = db.RiskDetails.Where(r => r.MitigantID == mt.MitigantId);

                    foreach (var r in rd)
                    {
                        db.RiskDetails.Remove(r);
                    }
                    db.SaveChanges();
                    db.MitigantsMaster.Remove(mitigant.First());
                    db.SaveChanges();
                }
            }
            return RedirectToAction("MitigantDetails", new { page = page });
    }

    //
    // POST: /Mitigant/Delete/5

    [HttpPost]
    public ActionResult Delete(int id, FormCollection collection)
    {
      try
      {
        // TODO: Add delete logic here

        return RedirectToAction("Index");
      }
      catch
      {
        return View();
      }
    }



    #region JSON Response Functions

    [HttpGet]
    public JsonResult Mitigants(int subRiskId)
    {
      List<MitigantMaster> mitigants = db.MitigantsMaster.Where(x => x.SubRiskId == subRiskId).ToList();
      return Json(mitigants, JsonRequestBehavior.AllowGet);
    }

    #endregion
  }
}

Rcsa.Web/Views/Mitigant/Create.cshtml
@using Rcsa.Web.Models
@model Rcsa.Web.Models.MitigantMaster

@{
    Layout = "~/Views/Shared/_SubLayout.cshtml";
    ViewBag.Title = "Create";
    RcsaDb db = new RcsaDb();
    var CompanyUsers = new List<int>();
    var compUsers1 = new List<int>();
    var adminConsultantUsers = new List<string>();
    var ids = new List<int>();
    if (User.IsInRole("Manager") || User.IsInRole("User"))
    {
        int mainComp = db.CompanyUsers.Where(x => x.UserId == WebSecurity.CurrentUserId).Select(x => x.UserId).FirstOrDefault();
        CompanyUsers = db.CompanyUsers.Where(x => x.CompanyId == mainComp).Select(x => x.CompanyId).ToList();
        compUsers1 = db.UserProfiles.Where(x => CompanyUsers.Contains(x.UserId)).Select(x => x.UserId).ToList();
        adminConsultantUsers.AddRange(Roles.GetUsersInRole("Admin"));
        adminConsultantUsers.AddRange(Roles.GetUsersInRole("Consultant"));
        ids = db.UserProfiles.Where(x => adminConsultantUsers.Contains(x.UserName)).Select(x => x.UserId).ToList();
    }
}


<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center;">Add Mitigant</h3>
<div class="form1">
    @using (Html.BeginForm("Create", "Mitigant", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        <fieldset>
            <label>Risk</label>
            @if (User.IsInRole("Manager") || User.IsInRole("User")) {
                @Html.DropDownList("ddlRisk", new SelectList(db.RiskMasters.Where(x => ids.Contains((int)x.CreatedBy) || compUsers1.Contains((int)x.CreatedBy)), "RiskId", "RiskName", @ViewBag.RiskSelected), "--- Select Risk---", new { id = "ddlRisk", style = "width:348px;height:36px;" })
            }
            else
            {
                @Html.DropDownList("ddlRisk", new SelectList(db.RiskMasters, "RiskId", "RiskName", @ViewBag.RiskSelected), "--- Select Risk---", new { id = "ddlRisk", style = "width:348px;height:36px;" })

            }

            <div class="clear"></div>
            <label>Sub Risk<span class="requiredFields">*</span></label>
            @if (User.IsInRole("Manager") || User.IsInRole("User"))
            {
                @Html.DropDownListFor(m => m.SubRiskId, new SelectList(db.SubRisksMaster.Where(x => ids.Contains((int)x.InsertedBy) || compUsers1.Contains((int)x.InsertedBy)), "SubRiskId", "SubRiskName", @ViewBag.SubRiskSelected), "--- Select Sub Risk ---", new { id = "ddlSubRisk", style = "width:348px;height:36px;" })

            }
            else
            {
                @Html.DropDownListFor(m => m.SubRiskId, new SelectList(db.SubRisksMaster, "SubRiskId", "SubRiskName", @ViewBag.SubRiskSelected), "--- Select Sub Risk ---", new { id = "ddlSubRisk", style = "width:348px;height:36px;" })

            }
                <div class="clear"></div>
            <label>Mitigant Name<span class="requiredFields">*</span></label>
            @Html.TextBoxFor(model => model.MitigantName, new { @MaxLength = "100" })

            <div class="clear"></div>
            <label>Description</label>
            @Html.TextAreaFor(model => model.MitigantDesc, new { @MaxLength = "3000" })
            <div class="clear"></div>
            <br />
            <label>&nbsp;</label>
            <button type="submit" value="Create" class="button1">Create</button>
            <div class="clear"></div>
            <input type="hidden" id="test" />
            <br />
        </fieldset>
    }
</div>
@if (!String.IsNullOrWhiteSpace(ViewBag.Error))
{
    <div class="error">
        @ViewBag.Error
    </div>   
}
@section scripts
{
    <script type="text/ecmascript">
        $(document).ready(function () {
            //$("#ddlSubRisk").prop("disabled",true);
            $('#ddlRisk').change(function () {
                bindSubRisks();
            });
            $('#ddlSubRisk').change(function () {
                bindMitigant();
            });
        });

        function bindSubRisks() {
            //$("#ddlSubRisk").prop("disabled", true);
            if ($("#ddlRisk").val() == "") return;

            var Param = { riskId: $("#ddlRisk").val() };

            $.getJSON("/SubRisk/SubRisks", Param, function (data) {
                //$("#ddlSubRisk").prop("disabled", data.length == 0);

                var items = "<option>-- Select Sub Risk --</option>";
                $.each(data, function (i, item) {
                    items += "<option value='" + item.SubRiskId + "' detail='" + item.SubRiskDesc + "'>" + item.SubRiskName + "</option>";
                });

                $("#ddlSubRisk").html(items);
            });
        }

        function bindMitigant() {
            debugger;
            //$("#ddlSubRisk").prop("disabled", true);
            if ($("#ddlSubRisk").val() == "") return;

            var Param = { SubRiskId: $("#ddlSubRisk").val() };

            $.getJSON("/Mitigant/Mitigants", Param, function (data) {
                //$("#ddlSubRisk").prop("disabled", data.length == 0);

                var items = "";// "<option>-- Select Mitigant --</option>";
                $.each(data, function (i, item) {
                    items += "<option value='" + item.MitigantId + "' detail='" + item.MitigantName + "'>" + item.MitigantName + "</option>";
                });

                $("#ddlMitigant").html(items);
            });
        }

    </script>
}

Rcsa.Web/Views/Mitigant/Details.cshtml
@model Rcsa.Web.Models.MitigantMaster

@{
    Layout = "~/Views/Shared/_SubLayout.cshtml";
    ViewBag.Title = "Details";
}
<h3 class="upcoming-head" style="margin-bottom: 5px; text-align:center;">Mitigants Details</h3>
<div class="form1" style="text-align: left; margin-left: 20px">
     <table id="hor-minimalist-b" style="margin: 7px 10px 62px -20px;" >
    <tbody >
        <tr>
            <td>
                <label>Mitigant Name </label>
            </td>
            <td>
                 @Html.DisplayFor(model => model.MitigantName)
            </td>
            
        </tr>

         <tr>
            <td>
               <label>Sub-Risk</label>
            </td>
            <td>
@Html.DisplayFor(model => model.SubRisksMaster.SubRiskName)
            </td>
            
        </tr>


         <tr>
            <td>
                 <label>Description</label>
            </td>
            <td>
                 @Html.DisplayFor(model => model.MitigantDesc)
            </td>
            
        </tr>

              

</tbody></table>




    <div style="float:right;clear:both;margin-bottom:20px;margin-right:40px;">
    <strong><u>@Html.ActionLink("Edit", "Edit", new { id = Model.MitigantId, page = ViewBag.CurrentlyOnPage })</u></strong> |
    <strong><u>@Html.ActionLink("Back to List", "MitigantDetails", new { page = ViewBag.CurrentlyOnPage })</u></strong>
        </div>
</div>


Rcsa.Web/Views/Mitigant/Edit.cshtml
@using Rcsa.Web.Models
@model Rcsa.Web.Models.MitigantMaster

@{
    Layout = "~/Views/Shared/_SubLayout.cshtml";
    ViewBag.Title = "Edit";
    RcsaDb db = new RcsaDb();
}

<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center;">Edit Mitigants</h3>
<div class="form1">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <fieldset>
            @Html.HiddenFor(model => model.MitigantId)
            <label>Risk</label>
            @*@Html.DropDownListFor(m => m.SubRisksMaster.RisksMaster.RiskId, new SelectList(db.RiskMasters, "RiskId", "RiskName"), "--- Select Risk ---", new { id = "ddlRisk" })*@
            @Html.DropDownList("ddlRisk", new SelectList(db.RiskMasters, "RiskId", "RiskName", Model.SubRisksMaster.RisksMaster.RiskId), "--- Select Risk ---", new { id = "ddlRisk", style = "width:348px;height:36px;" })
            <div class="clear"></div>
            <label>Sub Risk <span class="requiredFields">*</span></label>
            @Html.DropDownListFor(m => m.SubRiskId, new SelectList(db.SubRisksMaster.Where(x => x.RiskId == Model.SubRisksMaster.RisksMaster.RiskId), "SubRiskId", "SubRiskName"), "---Select Sub Risk---", new { id = "ddlSubRisk", style = "width:348px;height:36px;" })
            <div class="clear"></div>
            @*<label>Mitigants</label>
              @Html.DropDownListFor(m => m.SubRiskId, new SelectList("","MitigantId", "MitigantName",@ViewBag.MitigantSelected), new { id = "ddlMitigant",style="width:348px;height:36px;" })
             <div class="clear"></div>*@
            <label>Mitigant Name <span class="requiredFields">*</span></label>
            @Html.TextBoxFor(model => model.MitigantName, new { @MaxLength = "100" })
            <div class="clear"></div>
            <label>Description</label>
            @Html.TextAreaFor(model => model.MitigantDesc, new { @MaxLength = "3000" })
            <div class="clear"></div>
            <br />
            <label>&nbsp;</label>
            <input type="hidden" value="@Request.QueryString["page"]" name="page" />
            <button type="submit" value="Save" class="button1">Save</button>
        </fieldset>
    }
</div>

@section scripts
{
    <script type="text/ecmascript">
        $(document).ready(function () {
            //$("#ddlSubRisk").prop("disabled",true);
            $('#ddlRisk').change(function () {
                bindSubRisks();
            });
            $('#ddlSubRisk').change(function () {
                bindMitigant();
            });
        });

        function bindSubRisks() {
            //$("#ddlSubRisk").prop("disabled", true);
            if ($("#ddlRisk").val() == "") return;

            var Param = { riskId: $("#ddlRisk").val() };

            $.getJSON("/SubRisk/SubRisks", Param, function (data) {
                //$("#ddlSubRisk").prop("disabled", data.length == 0);

                var items = "<option>-- Select Sub Risk --</option>";
                $.each(data, function (i, item) {
                    items += "<option value='" + item.SubRiskId + "' detail='" + item.SubRiskDesc + "'>" + item.SubRiskName + "</option>";
                });

                $("#ddlSubRisk").html(items);
            });
        }
        function bindMitigant() {
            debugger;
            //$("#ddlSubRisk").prop("disabled", true);
            if ($("#ddlSubRisk").val() == "") return;

            var Param = { SubRiskId: $("#ddlSubRisk").val() };

            $.getJSON("/Mitigant/Mitigants", Param, function (data) {
                //$("#ddlSubRisk").prop("disabled", data.length == 0);

                var items = "";// "<option>-- Select Mitigant --</option>";
                $.each(data, function (i, item) {
                    items += "<option value='" + item.MitigantId + "' detail='" + item.MitigantName + "'>" + item.MitigantName + "</option>";
                });

                $("#ddlMitigant").html(items);
            });
        }
    </script>
}

Rcsa.Web/Views/Mitigant/MitigantDetails.cshtml
@model IEnumerable<Rcsa.Web.Models.MitigantMaster>

@{
    Layout = "~/Views/Shared/_SubLayout.cshtml";
    ViewBag.Title = "MitigantDetails";
}

<link href="~/Content/grid.css" rel="stylesheet" />
<h3 class="upcoming-head" style="margin-bottom: 5px; text-align: center;">Manage Controls/Mitigants</h3>

@using (Html.BeginForm())
{    
    <div class="searchBoxDiv">
        <span style="float: left">
            <input type="text" id="txtSearch" value="" name="keyword" placeholder="Search" style="width: 282px; margin-left: -23px;" />
            <input type="submit" value="Search" id="btnSearch" class="searchButton" />
            <input type="submit" value="Reset" id="btnReset" name="command" class="searchButton" />
        </span>
        <span style="float: right; margin-top: 6px; margin-right: 18px;"><strong><u>@Html.ActionLink("Add Mitigant", "Create")</u></strong></span>

    </div>
    <div style="height: 25px;"></div>            
}
<table class="minilist-b">
    <tr>
        <td>
            <div id="dvGrid">
                @if (Model != null)
                {
                    var gridTest = new WebGrid(Model, canPage: true, canSort: true, defaultSort: "MitigantName", rowsPerPage: 10, ajaxUpdateContainerId: "dvGrid");                    
                    @gridTest.GetHtml(
                tableStyle: "mGrid",
                alternatingRowStyle: "mGrid-alternating-row",
                          footerStyle: "pagination",
                          mode: WebGridPagerModes.All,
                          numericLinksCount: 10,
                          firstText: "First",
                          lastText: "Last",
                          previousText: "Prev",
                          nextText: "Next",
                columns: new[] {                  
                    gridTest.Column("MitigantName",header: "Mitigant" , style:"Wordwrap"),
                    gridTest.Column("SubRiskId",header: "Sub Risk",format: (item) => (item.SubRisksMaster.SubRiskName == null ? "" :item.SubRisksMaster.SubRiskName ), style:"Wordwrap"),
                    gridTest.Column("MitigantDesc",header: "Description", style:"Wordwrap"),                                        
                    gridTest.Column("",header:"",style: "grdSrNo",
                    format: @<text>
                    <div>
                        @Html.ActionLink("Edit", "Edit", new { id = item.MitigantId, page = ViewBag.CurrentlyOnPage }) |
                        @Html.ActionLink("Details", "Details", new { id = item.MitigantId, page = ViewBag.CurrentlyOnPage }) 

                        @{
                            if( !Rcsa.Web.Helpers.UsersHelper.isUserACompany() && !Rcsa.Web.Helpers.UsersHelper.isUserAManager())
                            {
                                @Html.Raw("|");
                                @Html.ActionLink("Delete", "Delete", new { id = item.MitigantId, page = ViewBag.CurrentlyOnPage }, new { @class = "del" })
          }
                        }


                    </div>
                    </text>
                    )
                })
                }
            </div>
            @if (@ViewBag.Mode == "Search" && Model.Count() == 0)
            {
                <div id="error" class="error" style="width: 747px;">No records found!!!</div>
            }
            <style>
                .grdSrNo
                {
                    width: 18%;
                    text-align: center;
                }

                .Wordwrap
                {
                    word-break: normal !important;
                }
            </style>
        </td>
    </tr>
</table>
